name: Deploy To GH Pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: AvengersCodeLovers/Avengers-Unit
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: dist/
